---
namespace: posit
name: posit_team
version: 0.1.0
readme: README.md

authors:
  - Posit Software, PBC
  - Brian Smith <brian@posit.co>

description: >-
  Ansible collection for installing and configuring Posit Team products
  (Posit Connect, Posit Workbench, and Posit Package Manager).

license:
  - MIT

license_file: ''

tags:
  - posit
  - rstudio
  - connect
  - workbench
  - packagemanager

dependencies: {}

repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker

build_ignore: []
