---
namespace: posit
name: posit_team
version: 0.1.0
readme: README.md

authors:
  - Posit Software, PBC
  - Brian Smith <brian@posit.co>

description: >-
  Ansible collection for installing and configuring Posit Team products
  (Posit Connect, Posit Workbench, and Posit Package Manager).

license_file: 'LICENSE'

tags:
  - posit
  - rstudio
  - connect
  - workbench
  - packagemanager

dependencies: {}

repository: https://github.com/posit-dev/ansible-collection-posit-team
issues: https://github.com/posit-dev/ansible-collection-posit-team/issues

build_ignore: []
