---
namespace: posit
name: team
version: 0.1.0
readme: README.md

authors:
  - Posit Software, PBC

description: >-
  Ansible collection for installing and configuring Posit Team products
  (Posit Connect, Posit Workbench, and Posit Package Manager).

license:
  - MIT

license_file: LICENSE

tags:
  - posit
  - rstudio
  - connect
  - workbench
  - packagemanager

dependencies:
  posit.tools: ">=0.2.0"

repository: https://github.com/posit-dev/ansible-collection-posit-team
documentation: https://github.com/posit-dev/ansible-collection-posit-team
homepage: https://github.com/posit-dev/ansible-collection-posit-team
issues: https://github.com/posit-dev/ansible-collection-posit-team/issues

build_ignore: []
