---
galaxy_info:
  author: Posit Software, PBC
  description: Install R versions using Posit r-builds
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "9"
        - "10"
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: SLES
      versions:
        - "15"

  galaxy_tags:
    - r
    - posit
    - rstudio

dependencies: []
